Setters now check for null
wolox-training/are-java pull request #14
Opened 2021-03-26 15:34 UTC by alisonreynoso

## Summary
- Model's setters check for null
- Added guava's precondition dependendency
## Trello Card
https://trello.com/c/xQP6Rjbi/29-agregar-validaci%C3%B3n-de-precondiciones-a-los-setters

2021-03-29 15:31 UTC, Jimenarosello reviewed
Nice job!! 😄  I recommend checking out the `checkArgument` method that allows to validate other things besides null fields, maybe you could add some validations with that method as well :)

2021-03-29 15:57 UTC, julianvasquez-wolox commented
As Jime said, you should apply some extra validations using checkArguments ( like no empty values or the year not to be greater than the actual year ) 😊

2021-03-29 15:58 UTC, julianvasquez-wolox requested changes
Check the comments 😁

2021-03-30 18:23 UTC, Jimenarosello approved these changes
Excellent job!! 😄

2021-03-30 18:23 UTC, Jimenarosello commented on src/main/java/wolox/training/models/Book.java
> +        Preconditions.checkArgument(year.matches("[0-9]+"), "The year field must contain only numbers");
Nice!! :D

2021-03-30 18:23 UTC, Jimenarosello commented on src/main/java/wolox/training/models/User.java
> +        Preconditions.checkArgument(name.chars().allMatch(Character::isLetter),
![tenor](https://user-images.githubusercontent.com/43755493/113037472-c9e9c100-916b-11eb-828c-58795bc50669.gif)

2021-03-30 18:26 UTC, julianvasquez-wolox approved these changes

2021-04-05 12:09 UTC, merged